config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'welcome/index'
  root 'welcome#index'
  devise_for :users, controllers: { sessions: "users/sessions",
                                    registrations: "users/registrations",
                                    passwords:  "users/passwords" }
  resources :question_categories, only: :destroy
  resources :questions, only: [:index, :show, :destroy]
  resources :answers,   only: [:create, :update, :destroy]
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :question_category
  has_many   :answers, dependent: :destroy
  has_many   :users, through: :answers

  validates_associated :answers
  validates :question_category_id, :text, presence: true
  validates :text, uniqueness: true, length: { minimum: 3 }

  scope :joins_answers, -> (user_id, is_answered) {
    query = <<-SQL
      LEFT OUTER JOIN answers
                   ON answers.question_id = questions.id
                  AND answers.user_id = #{user_id}
    SQL
    select('ARRAY_AGG(answers.id) AS answer_id, questions.*')
      .joins(query)
      .where("answers.id IS#{is_answered ? ' NOT ' : ' '}NULL")
      .group('questions.id')
  }
  scope :order_by_categories, -> {
    query = <<-SQL
      IDX(ARRAY(SELECT id
                  FROM  (SELECT id, concat(ancestry || '/', id) AS sort_string
                           FROM question_categories
                       ORDER BY sort_string ASC) AS category_id),
          question_category_id),
      id
    SQL
    order(query)
  }
  scope :next_or_previous_question, -> (user_id, is_answered, is_next, id) {
    sub_query = <<-SQL
      (          SELECT ARRAY_AGG(answers.id) AS answer_id, questions.*
                   FROM questions
        LEFT OUTER JOIN answers
                     ON answers.question_id = questions.id
                    AND answers.user_id = #{user_id}
                  WHERE answers.id IS#{is_answered ? ' NOT ' : ' '}NULL
               GROUP BY questions.id
      ) AS scope_questions
    SQL
    query = <<-SQL
      SELECT *
        FROM (SELECT *,
                     #{is_next ? 'LAG' : 'LEAD'}(id) OVER (
                       ORDER BY IDX(array(SELECT id
                                            FROM  (SELECT id,
                                                          CONCAT(
                                                            ancestry || '/',
                                                            id
                                                          ) AS sort_string
                                                     FROM question_categories
                                                 ORDER BY sort_string ASC)
                                              AS category_id),
                                     question_category_id),
                                id
                     )
                FROM #{is_answered == nil ? 'questions' : sub_query})
          AS next_or_previous_questions
       WHERE #{is_next ? 'lag' : 'lead'} = #{id}
    SQL
    find_by_sql(query)
  }

  def self.scope_questions(type_questions = 'All questions', current_user_id)
    res = Question.all if type_questions == 'All questions'
    res = Question.joins_answers(current_user_id, true)
            .group('questions.id') \
                       if type_questions == 'Questions with answers'
    res = Question.joins_answers(current_user_id, false)
            .group('questions.id') \
                       if type_questions == 'Questions without answers'
    res
  end

  def self.define_question(type_questions, current_user_id, id, is_next)
    is_answered = nil   if type_questions == 'All questions'
    is_answered = true  if type_questions == 'Questions with answers'
    is_answered = false if type_questions == 'Questions without answers'
    Question.next_or_previous_question(current_user_id, is_answered, is_next, id)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @questions = Question
                   .scope_questions(params[:type_questions], current_user.id)
                   .order_by_categories
                   .page(params[:page])
                   .per(params[:per])
    @length_questions = @questions.length
    @index_questions = 0
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @answer = Answer
                .find_by(question_id: @question.id, user_id: current_user.id)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_path }
      format.js
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/shared_show/_form_with_answer.html.erb
<%= form_for @answer, url: answer_path(@answer), method: :patch,
             remote: true do |f| %>
  <%= render 'questions/shared_show/text_area', f: f,
             question_id: question_id %><br />
<% end %><br />
<%= render 'questions/shared_show/buttons/button_destroy_answer' %>
<span id="data" data-answerid="<%= @answer.id %>"
      data-answeroldtext="<%= @answer.text %>">
</span>

app/views/questions/shared_show/_form_without_answer.html.erb
<%= form_for :answer, url: answers_path, remote: true do |f| %>
  <%= render 'questions/shared_show/text_area',
             f: f, question_id: question_id %><br />
<% end %><br />
<br />
<span id="data" data-answerid="0" data-answeroldtext=""></span>

app/views/questions/shared_show/_question.html.erb
<p class="segoepr-font text-primary">
  <%= QuestionCategory
    .return_question_category_full_name(@question.question_category_id) %>
</p>
<h2 class="header-font"><%= @question.text %></h2><br />
<% question_id = @question.id %>
<div class="row">
  <div class="col-md-2 col-md-offset-1"><br /><br /><br /><br />
    <%= render 'questions/shared_show/buttons/button_previous' %>
  </div>
  <div class="field col-md-6">
    <% if @answer %>
      <%= render 'questions/shared_show/form_with_answer',
                 question_id: question_id %>
    <% else %>
      <%= render 'questions/shared_show/form_without_answer',
                 question_id: question_id %>
    <% end %>
  </div><br />
  <div class="col-md-2"><br /><br /><br />
    <%= render 'questions/shared_show/buttons/button_next' %>
  </div><br />
</div><br /><br />

app/views/questions/shared_show/_text_area.html.erb
<div>
  <%= f.text_area :text, rows: 10, class: 'text-area' %>
  <%= f.hidden_field :question_id, value: question_id %>
</div>