config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'welcome/index'
  root 'welcome#index'
  devise_for :users, controllers: { sessions: "users/sessions",
                                    registrations: "users/registrations",
                                    passwords:  "users/passwords" }
  resources :question_categories, only: :destroy
  resources :questions, only: [:index, :show, :destroy]
  resources :answers,   only: [:create, :update, :destroy]
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @notice = notice
    @alert = alert
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_carousel.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0"
        class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
    <li data-target="#carousel-example-generic" data-slide-to="4"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag '01.jpg' %>
    </div>
    <div class="item">
      <%= image_tag '02.jpg' %>
    </div>
    <div class="item">
      <%= image_tag '03.jpg' %>
    </div>
    <div class="item">
      <%= image_tag '04.jpg' %>
    </div>
    <div class="item">
      <%= image_tag '05.jpg' %>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic"
     role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic"
     role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/welcome/_carousel_text.html.erb
<div class="carousel-notice">
  <p class="notice text-primary"><%= @notice %></p>
  <p class="alert text-error"><%= @alert %></p>
</div>
<% if user_signed_in? %>
  <h2>Hello, <%= current_user.name %>!
    <% if current_user %>
      <% if current_user.activated == false %>
        <%= 'You are not activated yet' %>
      <% end %>
    <% end %>
  </h2><br />
  <h3>
    <% if can? :access, :rails_admin %>
      <td>
        <span class="tab2 menu-animation">
          <%= link_to 'Administration', rails_admin_path %>
        </span>
      </td>
    <% end %>
    <% if can? :index, Question %>
      <td>
        <span class="tab2 menu-animation">
          <%= link_to 'Questions',
                      questions_path(type_questions: 'All questions'),
                      class: 'red', id: 'jumping' %>
        </span>
      </td>
    <% end %>
    <% if current_user.activated == true %>
      <td>
        <span class="tab2 menu-animation">
          <%= link_to 'Edit profile', edit_user_registration_path %>
        </span>
      </td>
    <% end %>
      <td>
        <span class="tab2 menu-animation">
          <%= link_to 'LOG OUT', destroy_user_session_path,
                                 method: :delete  %>
        </span>
      </td>
  </h3>
<% else %>
  <h2>Hello, Guest!</h2><br />
  <h3>
    To get access -
    <%= link_to 'LOG IN', new_user_session_path %>, if you have an account,
    or <%= link_to 'SIGN UP', new_user_registration_path %>
    - if you haven't.<br />
  </h3>
<% end %>

app/views/welcome/index.html.erb
<span class="main-text">
  <div class="container">
    <div class="carousel-caption">
      <%= render'welcome/carousel_text' %>
    </div>
  </div>
</span>
<h2 class="about">
  Do you know about the benefits of questions?<br />
  Answering the right questions, you get to know yourself.<br />
  Questions are a key to self-awareness, personal growth and happiness.
  <br /><br />
  Here are some important questions for your self-reflection, by yours truly.
  <br /><br />
  These questions will help you focus on what’s important to you
  and what you want.
</h2>
<h4 class="link-to-site">
  WebSite created using
  <%= link_to '101 Important Questions To Ask Yourself',
              'http://personalexcellence.co/blog/101-questions/' %>
</h4>