config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'welcome/index'
  root 'welcome#index'
  devise_for :users, controllers: { sessions: "users/sessions",
                                    registrations: "users/registrations",
                                    passwords:  "users/passwords" }
  resources :question_categories, only: :destroy
  resources :questions, only: [:index, :show, :destroy]
  resources :answers,   only: [:create, :update, :destroy]
end

app/views/questions/shared_show/buttons/_button_destroy_answer.html.erb
<div>
  <%= link_to 'Delete the answer', answer_path(@answer),
              method: :delete,
              data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
</div>

app/views/questions/shared_show/buttons/_button_next.html.erb
<% if next_question = Question.define_question(params[:type_questions],
                                               current_user.id,
                                               @question.id,
                                               true)[0] %>
  <%= link_to 'Next', question_path(next_question,
                                    type_questions: params[:type_questions]),
              id: 'next', class: 'btn btn-success',
              remote: true if next_question %>
<% end %>

app/views/questions/shared_show/buttons/_button_previous.html.erb
<% if previous_question = Question.define_question(params[:type_questions],
                                                   current_user.id,
                                                   @question.id,
                                                   false)[0] %>
  <%= link_to 'Previous', question_path(previous_question,
                                       type_questions: params[:type_questions]),
              id: 'previous', class: 'btn btn-primary',
              remote: true if previous_question %>
<% end %>